### ISSUE TITLE
Data discrepancies in US States list

### ISSUE THREAD

**Issue by kinabalu** [pr3d4t0r/COVIDvu#100]
If Total US is 1281 how can Unassigned be 1235 when Washington is clearly at 367 which puts it over the "Total".

**Comment by pr3d4t0r** [comment]
Because CSSE COVID-19 is double-counting somewhere.  The data is all fuck'd.  I'll see what I can do in [issue 0096](https://github.com/pr3d4t0r/COVIDvu/issues/96) about this one.  I tried to fix it yesterday and we came up 30% short in reported vs actual.  I may force those into _Unassigned_.
