### ISSUE TITLE
Find the region links for the following missing regions

### ISSUE THREAD

**Issue by kinabalu** [pr3d4t0r/COVIDvu#109]
American Samoa
Marshall Islands
Micronesia
Northern Marianas
Puerto Rico
West Virginia

can add to the `REGION_URLS` array in `./src/constants/index.js`

**Comment by jaryaman** [comment]
In #116 I remove these as US states following a chat with @pr3d4t0r. Let me know if you'd rather I put them back in

**Comment by kinabalu** [comment]
poor West Virginia

**Comment by kinabalu** [comment]
I think we should have any US territories in the state list

**Comment by jaryaman** [comment]
Done! #116 should have the US territories back in.

**Comment by dlwhitehurst** [comment]
Andrew, can you point me to a valid link for a state e.g.? I'm assuming it's just a public link with COVID-19 data? Schema matter? Or specific data points? I'll take on the hunt, but clear me up a little on what I'm looking for. You want URLs for the regions above right? And, then you need them enumerated in an array in the Javascript for use.

**Comment by kinabalu** [comment]
@dlwhitehurst take a look at the links that already exist, in the json at the specified location above and see that it's a state-specific website, it generally has info for that state / region, and might have confirmed cases / metrics

**Comment by pr3d4t0r** [comment]
@dlwhitehurst, @kinabalu  - This is implemented and rolled out to production.  Also, our spy @kotek14 found the counties data hidden somewhere in the world wide web.  Closing this one.
