### ISSUE TITLE
Fill in country url's in the constants/index.js variable REGION_URLS

### ISSUE THREAD

**Issue by kinabalu** [pr3d4t0r/COVIDvu#112]
Most of the US States are all filled in, we need country links. The health organizations that people can go to to get more information would be great. We link off to them in the Stats page and soon will be in the graphs pages as well.

**Comment by dlwhitehurst** [comment]
Here's one for Germany: https://www.infektionsschutz.de/coronavirus/

I think I can get these. I also would like to code in the Government Services: piece in the React app and do the same as the US stuff. Just a reply to let me know I'm on the right track. These will be the official, Health Dept., Ministry of Health, etc. sites?

**Comment by dlwhitehurst** [comment]
Italy - http://www.salute.gov.it/nuovocoronavirus
Spain - https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov
China - Unknown
France - https://www.gouvernement.fr/info-coronavirus
Iran - Withholding (no transparency)
United Kingdom (UK) - https://www.gov.uk/coronavirus
Switzerland - https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov.html

**Comment by dlwhitehurst** [comment]
Submitted Pull Request (PR) https://github.com/VirusTrack/COVIDvu/pull/443

**Comment by dlwhitehurst** [comment]
Adding source for World Health Ministries - https://www.gfmer.ch/Medical_search/Ministry_health.html
