### ISSUE TITLE
Update the total cases to reflect the current selected regions

### ISSUE THREAD

**Issue by kinabalu** [pr3d4t0r/COVIDvu#115]
Opt for highest number if more than one selected

**Comment by pr3d4t0r** [comment]
@kinabalu - Please provide more details -- thanks!

**Comment by pr3d4t0r** [comment]
I don't understand what this means.

**Comment by kinabalu** [comment]
i labeled it frontend, so it's a note for that. when selecting items on the frontend may change some of the totals so it's dynamic with what's been selected. this isn't a data issue.
