### ISSUE TITLE
Update the README with website link, image

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#118]

**Comment by dlwhitehurst** [comment]
Tell me where the link and image are. I'm working on the README overall for step by step and seeing data for newcomers easily.

**Comment by pr3d4t0r** [comment]
@dlwhitehurst - I want to post an image of the virustrack.live website and one of the lab, both will coincide with social media posts on Monday.  I started work on this too, let's merge efforts.
