### ISSUE TITLE
Legends obscure data with multiple time series

### ISSUE THREAD

**Issue by jaryaman** [pr3d4t0r/COVIDvu#122]
When plotting multiple time series, the legend sits in the top right and obscures the data.

**Comment by kinabalu** [comment]
we're now putting the legend outside of the graph, @jaryaman please re-open if you see any issues with that approach

**Comment by jaryaman** [comment]
Still seems like a problem

![image](https://user-images.githubusercontent.com/7837158/76748044-0372a880-6772-11ea-8410-72d4df1d868b.png)

**Comment by kinabalu** [comment]
yeah, I changed it back again because it makes the graphs nicer on mobile. thanks for re-opening.

**Comment by kinabalu** [comment]
@jaryaman can you check again? moved to the bottom and centered

**Comment by kinabalu** [comment]
I'm going to say now that it's at the bottom it's not obscuring, please re-open if not.
