### ISSUE TITLE
README needs to address two objectives

### ISSUE THREAD

**Issue by dlwhitehurst** [pr3d4t0r/COVIDvu#125]
The file README.md needs to address two objectives:

1. It should provide clear instructions to get Jupyter Notebook running to be able to visualize the public data (User Focus)
2. It should also provide details for any developer to be able to easily contribute.

**Comment by pr3d4t0r** [comment]
Excellent, thank you.

Would you like to contribute with that?  It'll be the starting point for you to go down the rabbit hole.  I made you a contributor, ping me on IRC or here if you have questions about how to get those things going.

If there were issues running the lab with the instructions I provided please either describe them here or go ahead and start work on the README in a fork.  Please add yourself to the `./CONTRIBUTORS.md` page as well.  When done request a fork merge.

Thanks and looking forward to working with you on this!

**Comment by dlwhitehurst** [comment]
PR #151 - submitted to update README with a user-focus (using Jupyter notebook).

**Comment by dlwhitehurst** [comment]
Continuing with Developer Focus #2. JupyterLab (Docker Image) did not work for me following the README instructions on my macbook pro. I've had Python but didn't try virtualenv first. Also, I was limited on space when trying to install things to get environment working. Starting from scratch again and then wish to document README with solid instructions.

**Comment by pr3d4t0r** [comment]
Are you making any progress with this, combined with the stuff I mentioned to you in the pull request?  Please let me know.  That pull request's been lagging for almost a week, we'd love to have it.  Please update in comments here or there -- thanks!

**Comment by dlwhitehurst** [comment]
Closing this issue because interested parties can just view the data (reason for the project) at https://virustrack.live
