### ISSUE TITLE
Display unassigned US cases and accuracy disclaimer

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#127]
Hi!

There is a daily number of unassigned cases that are consolidated at the end of the day in the CSSE dataset.  These are calculated as:
```python
totalUS - sum(allStatesAndTerritories)
````
There's a single entry at the end of the table, with the unassigned cases:
```python
dataUS['Unassigned'][today]
```
Use the unassigned count for the current day, in a disclaimer with text like:

_The sum of all states and territories may differ from the total because of delays in CDC and individual states reports consolidation.  Unassigned cases today = 42_

**Comment by pr3d4t0r** [comment]
The disclaimer ought to appear in the US regions tab too.

**Comment by pr3d4t0r** [comment]
Ditto global - China vs Outside doesn't add up anymore because they come from the static dataset,  not from BNO.  I'd suggest eliminating "Outside China" altogether at this point -- there are almost as many cases, and by Sunday morning there'll be more, than in China.

**Comment by kinabalu** [comment]
Added. I've filtered out "!Outside China" as per the last comment, makes sense to me too. No notification on the Global page right now, re-open if you think one is warranted, though we don't have an Unassigned.
