### ISSUE TITLE
Fix homologized names

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#132]
Hi Andrew!

Here are the "missing names" from the list.  Feel free to resolve the JSON-to-human translation with whatever rules you impose.  Data files will not change going forward.  No more UK in one file, United Kingdom in the next drop.

https://github.com/pr3d4t0r/COVIDvu/blob/master/work/experiments/virustrack_live-validation-tests.ipynb

Proof the data are correct.

Thanks and cheers!

**Comment by kinabalu** [comment]
Fixed and deployed.
