### ISSUE TITLE
Set <meta http-equiv='refresh' content='300'> header for auto-refresh

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#135]
I don't see this as a must and 100% fine if you decide against it.  I thought it'd be neat.  It'll also drive my S3 bill higher, though!

Cheers!

**Comment by kinabalu** [comment]
we're doing auto-refreshes within React itself, and I believe with the new design being prepped in #189 we should have a way of showing loaders when the site reloads so it's more apparent
