### ISSUE TITLE
Possible data source (not sure of its sources)

### ISSUE THREAD

**Issue by jottinger** [pr3d4t0r/COVIDvu#143]
https://covid19.mathdro.id/api

**Comment by pr3d4t0r** [comment]
Hi Joe!

Thanks for submitting this.  The API is neat but the data is stale.  The service is a front-end to the data from JH CSSE, which we already have.  JH CSS is great up until the last refresh, up to 24 hours ago.  It's stale after that refresh, now within less than 30 minutes.

Compare what you see at https://covid19.mathdro.id/api for totals, against the output from this:

```bash
curl -s "https://virustrack.live/site-data/confirmed.json" | jq '.["!Global"]'
```

We need help with coding more than with data sources...  hint, hint...   please let us know if you want to jump in the fray!

Thanks for your submission and cheers!
