### ISSUE TITLE
Compress JSON bundles before uploading

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#150]
Much cheaper bandwidth cost.

@kinabalu - Did you check if the format is equivalent to `zcat filename.json > filename.json.gz`?  Thanks!

Low priority

**Comment by kinabalu** [comment]
it may be but i'm under the impression that cloudfront is doing the compressing now for us. if we need to do it on upload and download, we'll have to change some frontend code to process

**Comment by pr3d4t0r** [comment]
Yeah, and at $20/mo it's fine to leave them as-is.  Closing this issue.
