### ISSUE TITLE
Create a dashboard/homepage which includes quick stats and embeds multiple graphs

### ISSUE THREAD

**Issue by kinabalu** [pr3d4t0r/COVIDvu#152]
the idea would be to pull in quick numbers and stats that can be seen great on desktop or mobile, as a homepage of sorts. and it would auto-update as well.

must be responsive on mobile.

@jaryaman @pr3d4t0r thoughts?

**Comment by jaryaman** [comment]
Sounds like a good idea to me.

Another suggestion. Is it possible to disable the plotly zooming when on mobile? The scrolling is difficult with the interactive plots. 

I have no idea how easy this is to implement so feel free to ignore! But if it's easy to implement, could be a nice alternative.

**Comment by kinabalu** [comment]
implemented!
