### ISSUE TITLE
Add Creative Commons content license notice to website

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#177]
Hi!

Licenses information:  https://creativecommons.org/licenses/

- Please use the logo
- Let's place this between the Twitter line (or at the same level) and the rest of the lines on the footer
- Link to license text:  https://creativecommons.org/licenses/by-sa/4.0/
- License text for the footer:  _Except where otherwise noted, content on this site is licensed under the Creative Commons Attribution-ShareAlike 4.0 International license._

Full details on how to integrate this are here:  https://creativecommons.org/platform/toolkit -you may skip most of it and go straight to the HTML tags.  Most of it explains meanings like the main document.

I will add the link to the license text to the LICENSES.txt file in the project on the branch that I'm in; no need to put it there to avoid a Git merge conflict.

Thanks!!!

**Comment by kinabalu** [comment]
Done.
