### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by lucasmarohn** [pr3d4t0r/COVIDvu#189]
Hey team, love the work that's been done so far here.
I created [mockups for some new UI](https://www.figma.com/proto/GVZkj5qekf1sPQVGo3F1Ri/Virus-Track?node-id=1%3A2&viewport=138%2C146%2C0.17279212176799774&scaling=scale-down) which I've attached to this issue.

I thought this project could benefit from a design that departed from the dark, cluttered, "mission control" style of the [JHU tracker](https://coronavirus.jhu.edu/map.html) and give this project a serious tone—while still feeling simple, inuitive, and accessible.

The headline font is Archivo which is available through google fonts, and the body fonts will be the machine default (SF Pro on mac, Roboto on windows, or Arial/Helvetica on older devices) so we can maintain speedy load times.

![Dashboard Page](https://user-images.githubusercontent.com/9707565/77103792-3c13bb80-69d8-11ea-91e2-0ca494aca6ec.png)
![Region Page](https://user-images.githubusercontent.com/9707565/77103794-3cac5200-69d8-11ea-93c2-c0409e7c826a.png)

![Dashboard Mobile](https://user-images.githubusercontent.com/9707565/77103783-38803480-69d8-11ea-96c8-59e599167375.png)

**Comment by kinabalu** [comment]
I love this look and feel, as mentioned I'll work closely with you on implementing this on top of what we already have

**Comment by kinabalu** [comment]
New design looks very very good. Thank you!
