### ISSUE TITLE
Multi-Select UI -> Checkboxes

### ISSUE THREAD

**Issue by lucasmarohn** [pr3d4t0r/COVIDvu#192]
The multi-select inputs work fine on desktop—though they don't allow for much visual customization—and the user experience leaves much to be desired on mobile devices, especially when trying to navigate through hundreds of countries that aren't in alphabetical order. 

The existing functionality and current look can be accomplished using checkboxes instead of a multi-select. And moving to checkboxes will enable contributors to:
- Have complete more control over the look and feel 
- Keep the UI consistent across devices
- Easily add features such as filters and search 

Consider changing the multi-select for the countries/states/regions and using checkboxes instead.

**Comment by pr3d4t0r** [comment]
Yup, thanks.

I found it here:  <img src='https://i.imgur.com/jJekgW0.png'>

**Comment by kinabalu** [comment]
Fixed, looks great.
