### ISSUE TITLE
Query string parameters don't select countries

### ISSUE THREAD

**Issue by gbevin** [pr3d4t0r/COVIDvu#225]
Seems the URL doesn't properly select the countries that are in it, for instance: https://virustrack.live/covid?graph=Cases&region=Italy&region=US still selects Global and China

**Comment by kinabalu** [comment]
@gbevin thanks for this, was related to some query parameters that were being used early on, and we've been narrowing down and using just region now. If you have a moment to re-test, that would be wonderful, I think we can probably close this as it's likely been fixed now.

**Comment by gbevin** [comment]
It works now, thanks!
