### ISSUE TITLE
Add switch / new action in Redux for returning log scale values for confirmed + deaths

### ISSUE THREAD

**Issue by kinabalu** [pr3d4t0r/COVIDvu#228]
This will have implications on the frontend UI code and also the domain itself to return values that are logarithmic in scale.

Every value in a series should be recalculated to use `Math.log(1+n)` per @jaryaman

**Comment by lucasmarohn** [comment]
Mockup
<img width="664" alt="Screen Shot 2020-03-21 at 4 09 32 PM" src="https://user-images.githubusercontent.com/9707565/77240562-ada06500-6ba4-11ea-8b3d-48c430a5cee3.png">

**Comment by kinabalu** [comment]
Fixed.
