### ISSUE TITLE
Add UI logarithmic y-axis toggle

### ISSUE THREAD

**Issue by lucasmarohn** [pr3d4t0r/COVIDvu#237]
<img width="664" alt="Screen Shot 2020-03-21 at 4 09 32 PM" src="https://user-images.githubusercontent.com/9707565/77238566-61e2c100-6b8e-11ea-87b3-845cbdc801df.png">

**Comment by jaryaman** [comment]
I'd suggest that when the user toggles the logarithmic scale, under the hood you +1 to the total number of cases, and then display on log scale. So in practice you'd display Log(cases + 1). This just avoids taking Log(0).

**Comment by kinabalu** [comment]
fixed and in prod now.
