### ISSUE TITLE
"Compare U.S. States" Button Not Visible

### ISSUE THREAD

**Issue by bitspace** [pr3d4t0r/COVIDvu#238]
The "Compare U.S. Regions" button is visible, but there is no button for "Compare U.S. States". This button was previously visible. See screenshot. Firefox 74.0 Pop_OS (Ubuntu)
![covidvu-dashboard-01](https://user-images.githubusercontent.com/649833/77240028-ab93d180-6bb7-11ea-963e-bdebcbdc383a.png)

**Comment by kinabalu** [comment]
Thanks for filing, would you mind checking on that again, we just made another push that should fix that issue.

**Comment by bitspace** [comment]
Fixed! That was quick.
