### ISSUE TITLE
Fully responsive charts

### ISSUE THREAD

**Issue by lucasmarohn** [pr3d4t0r/COVIDvu#239]
At the moment, all charts are locked at a 450px height and a responsive width.

This means that as items are added to the chart/legend, the graph height decreases as the legend height increases. It also appears to be limiting the max width of the charts.

The charts should expand to take up the full width of their container, and their height should increase accordingly to accommodate that.

![unnamed](https://user-images.githubusercontent.com/9707565/77240651-6a92c180-6ba5-11ea-9319-9059b25906c4.png)

**Comment by kinabalu** [comment]
@lukemarohn feels like we're doing this, can you review? if you agree let's close this out.

**Comment by kinabalu** [comment]
Feels like this is done, so closing.
