### ISSUE TITLE
Create raw data downloads from selections

### ISSUE THREAD

**Issue by jtdavies** [pr3d4t0r/COVIDvu#249]
If I choose to look at the data from France, Spain and Germany (for example) it would be useful to be able to find a link that allowed me to download the raw data for countries/states I have selected.

**Comment by kinabalu** [comment]
In what format would make sense? a .csv?

**Comment by pr3d4t0r** [comment]
@kinabalu - Wouldn't JSON be easier on everyone?  We already have the data in JSON format and in JavaScript dictionaries.

**Comment by jtdavies** [comment]
I would suggest CSV first priority, JSON close behind.
I’m imagining news, media etc. using the data and they’re not generally JSON literate.

**Comment by kinabalu** [comment]
@lukemarohn can we get an icon for a dropdown perhaps for downloading the CSV file for a specific graph being viewed?
