### ISSUE TITLE
Add Europe view in addition to US

### ISSUE THREAD

**Issue by jtdavies** [pr3d4t0r/COVIDvu#251]
Given that Europe is currently at the centre of the outbreak is would be nice to add a Europe tab rather like the US but listing the EU's 28 counties.

**Comment by kinabalu** [comment]
and by EU counties do you mean the countries?

**Comment by jtdavies** [comment]
Oops, typo sorry. By Europe I mean geographic continent or Europe (including EU, EEA, Single Market and the outliers like Andorra, Channel Islands, former Yugoslavia etc. A tab where people physically in Europe can see where they and their neighbours stand just as a US person will do with local states.
