### ISSUE TITLE
Reduce hero size on iPad for improved viewing of page data 

### ISSUE THREAD

**Issue by mmorper** [pr3d4t0r/COVIDvu#253]

**Comment by mmorper** [comment]
On an iPad in landscape, too much real estate is consumed vertically. So much so, no data is seen (see attachment). 
![3790A0CA-3DF5-4DAC-B367-25AE2966C143](https://user-images.githubusercontent.com/15195056/77277023-46a0b000-6c79-11ea-9507-3e94a58427ee.jpeg)

**Comment by kinabalu** [comment]
I'll leave this up to @lukemarohn -- let us know if you think we can use the space more optimally, given that the website is definitely beautiful already
