### ISSUE TITLE
Improve context of “beds” in dashboard

### ISSUE THREAD

**Issue by mmorper** [pr3d4t0r/COVIDvu#255]
It’s cool to see this data,  it it’s context is not clear. Is this the total number of beds? Available beds? Might be helpful to have an “info” tooltip next to each column that helps viewers understand definitions for each column label.
![752FDA8B-9A03-4F91-825E-911254F88C1F](https://user-images.githubusercontent.com/15195056/77277350-f118d300-6c79-11ea-9b63-b962aec0b01a.jpeg)

**Comment by kinabalu** [comment]
Duplicate of #235
