### ISSUE TITLE
Sort by column header in stats

### ISSUE THREAD

**Issue by mmorper** [pr3d4t0r/COVIDvu#256]
I would love to be able to click on a column label to sort (Descending, ascending).

**Comment by kinabalu** [comment]
Definitely something on our radar, and shouldn't be too difficult. I don't know why you'd want to show an ascending view of any of the columns though? Is that significant in any way?

**Comment by kinabalu** [comment]
Sorting descending is now enabled for Confirmed, Deaths, and Mortality Rate for Global and US, and for Confirmed and Deaths at the US_Counties filter when in table view.
