### ISSUE TITLE
Set default country

### ISSUE THREAD

**Issue by mmorper** [pr3d4t0r/COVIDvu#257]
I think you should consider the ability to provide users with the choose of what country to default into the UI. Personally, I’m good with United States,  but I suspect the queen of England would prefer to see the U.K.

**Comment by kinabalu** [comment]
I'm wondering how we'd do this in a way that was simple enough in the UI. I've considered adding the ability for the UI to just automatically save your last selection so when viewing a page that showed up. 

@lukemarohn any thoughts here? Is there a place in the UI to do this cleanly? Or would setting some details in localStorage make the most sense?

**Comment by kinabalu** [comment]
@mmorper we also have permalink for whenever you change something in the UI, so you should be able to bookmark the current view, and clicking that link will pull those countries or regions depending on the graph

**Comment by kinabalu** [comment]
I feel like permalink is good here, as we don't want to add any unnecessary user state if we don't have to. please feel free to re-open if you'd like to discuss further

**Comment by mmorper** [comment]
I think surfacing a US is an inappropriate bias.
