### ISSUE TITLE
Sub state detail

### ISSUE THREAD

**Issue by mmorper** [pr3d4t0r/COVIDvu#258]
Unclear if your data source(s) provide this precision, but it would be awesome to see sub state (region) date. Example: county level reporting for the state of California. See how Bing is doing it — I got it to work for the state of Florida https://www.bing.com/covid

**Comment by kinabalu** [comment]
we do have some county reported data, if you click on the "Stats" table and select "US Counties" you'll be able to select the U.S. State to filter, and see all the reported info we have. It's no historic, but pulled once daily.

The view for Florida on that site is similar to a link we've seen where the data probably came from: https://fdoh.maps.arcgis.com/apps/opsdashboard/index.html?fbclid=IwAR2lYjGL7yHakqtGP1clRws6BsO8mCLTRpRiQIxgbvZa7Mr3PfMu6OgTScE#/8d0de33f260d444c852a615dc7837c86

hoping that more of this data becomes available. what would you suggest?

**Comment by kinabalu** [comment]
we do offer county-level data now under https://virustrack.live/stats?filter=US_Counties and as always we're looking for more data, always.

Going to close this for now.
