### ISSUE TITLE
CRITICAL - update the VirusTrack footer to include new county data sources

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#284]
Reference:  CSBS
URL:  https://www.csbs.org/information-covid-19-coronavirus

Please place it between CDC and ECDC.  Thanks!

**Comment by pr3d4t0r** [comment]
Assigned @kinabalu and @lukemarohn -- whoever gets to it first, please.  Cheers!

**Comment by kinabalu** [comment]
done.
