### ISSUE TITLE
Add ability to select countries with default being US/UK

### ISSUE THREAD

**Issue by kinabalu** [pr3d4t0r/COVIDvu#31]
Add a multi select along with reading from the sample JSON given by @pr3d4t0r

**Comment by jaryaman** [comment]
Hey @kinabalu! Not sure I understand this issue -- is it just that you'd like `COVIDvu.ipynb` to default to US and UK? The notebooks as they currently are have the ability to select multiple countries, just that the default is "!Global" and "!Outside Mainland China". 

Happy to switch to US/UK -- just checking I understand the issue :)

**Comment by kinabalu** [comment]
@jaryaman this wasn't for the python notebooks at all, frontend only. I've modified to denote that as a label.

**Comment by kinabalu** [comment]
working now.
