### ISSUE TITLE
Open Graph Image

### ISSUE THREAD

**Issue by lucasmarohn** [pr3d4t0r/COVIDvu#312]
As we ramp up visibility on this project, we should have an OG Image that'll pop up automagically above links on Facebook, Twitter, Linkedin, etc.

**Comment by kinabalu** [comment]
that sounds very awesome, thank you!

**Comment by lucasmarohn** [comment]
How's this? @kinabalu @pr3d4t0r 

Maintaining the current graphical elements + nice big logo and a preview of our friendly UI

![og-image](https://user-images.githubusercontent.com/9707565/77705163-32f89080-6f7c-11ea-8ae0-2eb5f57aa90f.png)

**Comment by kinabalu** [comment]
LGTM
