### ISSUE TITLE
Testing Data

### ISSUE THREAD

**Issue by danieldesignnomad** [pr3d4t0r/COVIDvu#332]
I would love to see testing data added to VirusTrack. Here's a good resource I found today: https://covidtracking.com/

It would be great to pull from here and integrate into the site.

–DL

**Comment by pr3d4t0r** [comment]
@danieldesignnomad - Interesting idea.  How would you describe the workflow?  Thanks!

**Comment by danieldesignnomad** [comment]
Not sure I follow re: workflow? You mean how to display the information?

**Comment by pr3d4t0r** [comment]
@danieldesignnomad - I see what this is now -- COVID-19 testing data, not a workflow for testing the `covidvu` package or the VirusTrack website.  On it -- I think we'll prioritize this one if the data source proves to be credible.  Thank  you very much!  Stay tuned for updates.

**Comment by pr3d4t0r** [comment]
@danieldesignnomad - We're going to work on this one next -- thank you very much for the recommendation.

**Comment by danieldesignnomad** [comment]
Okay, fantastic! I think the data is as accurate as what the States are reporting because that’s where they’re pulling from. But I’m not sure because this is all above my pay grade.
