### ISSUE TITLE
How does the frontend handle missing data for the current day

### ISSUE THREAD

**Issue by kinabalu** [pr3d4t0r/COVIDvu#338]
This has implications throughout the entire site, how do we handle current day data being missing in the data files? Do we show '-' and turn off certain features? Do we check for yesterday and put a notice up automatically?

**Comment by kinabalu** [comment]
@pr3d4t0r @jaryaman would love comments on how we handle this, what we feel is an appropriate thing to show to end-user should this occur again

**Comment by jaryaman** [comment]
@kinabalu I reckon displaying yesterday and displaying a notice is the way to go. Yesterday's data always comes from John Hopkins, whereas today is an amalgam of patches I think. So yesterday has fewer moving parts and ought to be relatively stable (until John Hopkins breaks everything by changing how they supply data).

**Comment by pr3d4t0r** [comment]
@kinabalu - I concur - if we miss a day => make `todayCases = yesterdayCases`.  Some country reports show a flat increase on occasion (look at the plot for Italy).  There are days when nothing was reported, it shows flat on two consecutive days, then a jump.
