### ISSUE TITLE
Stats Page: Add Recovered/Percentages

### ISSUE THREAD

**Issue by danieldesignnomad** [pr3d4t0r/COVIDvu#345]
It would be great to see a column for Recovered added to the Stats page. Makes it all a bit less "doom and gloom." Also, consider adding %  in the New Cases and New Deaths column? I've seen this on other tracking sites. I wouldn't create an additional column, just something like: 

**New Cases**
17,490 (21%)

**Comment by kinabalu** [comment]
Recovered is never adequately reported and is generally just wrong because when people get better they don't tend to report back all the time. So we're probably never going to report that.

Re: percentages, new cases / total. I might see that working. @pr3d4t0r @jaryaman ?

**Comment by danieldesignnomad** [comment]
I get that, no worries. On that note: mortality rates are also inaccurate and likely overestimated in many areas of the world. 

I do think adding the percentage in () to the cases is still a good idea. :)

**Comment by jaryaman** [comment]
Yep, I think % is a good idea!
