### ISSUE TITLE
Add silent conda upgrade to Dockerfile

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#347]

**Comment by pr3d4t0r** [comment]
It also needs to be added to the `work/Makefile` refresh target.  There's a conda call in the Makefile, but it requires user attention; temporary implementation until this ticket is solved.

**Comment by pr3d4t0r** [comment]
Actually - this needs to be thought at a wider level.  We CANNOT assume that Conda/Anaconda is installed, because it doesn't exist in bare metal, only in the mini lab.  We need to find out all the dependencies for running the `covidvu.predict` module in a standard Python 3.7+ virtual environment, without Conda.  Assigned to @jaryaman

**Comment by jaryaman** [comment]
This is related to #348. Upon running `covidvu.predict` in the minilab, we get the warning

```
WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'
```

The purpose of `mkl` is for multi-threading of multiple MCMC chains. I presume it works when `mkl` isn't installed because it just defaults to 1 thread?

I was going to try and simply run `conda install mkl-service` in the mini-lab and add it to `Dockerfile` to resolve #348, but now if we need to get this working independently of Conda then I may need your help.

**Comment by pr3d4t0r** [comment]
@jaryaman - Thanks!  See if you can shake this bear and report, it's not an urgent matter.  The heavy lifting will happen when I go to the server and run mkl and theano on the metal.

**Comment by dlwhitehurst** [comment]
Would you @pr3d4t0r know why Unbuntu is having GPG issues with their apt repo? I've tried apt-get clear and also moving the cache `mv /var/lib/apt/lists /tmp` and still getting:

`W: GPG error: http://security.ubuntu.com/ubuntu bionic-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.ubuntu.com/ubuntu bionic-security InRelease' is not signed.`

The request is only trying to update, upgrade, and install packages from apt into the "FROM" jupyterlab image after the fact when I'm trying to create an image from the Dockerfile. I have the .bash_profile and the Dockerfile in an empty directory. Do I need some public key that I'm missing?  Others on the net have cleared this with 1) docker prune images (did that) 2) docker prune containers (did that) and 3) apt clean

**Comment by pr3d4t0r** [comment]
@dlwhitehurst - I'm not sure about what you're doing.  Try:

`make image`

From the top-level directory (*NOT* from `./work`) and that should build the image.

I invited you to our Schlack channel a few minutes ago.

**Comment by dlwhitehurst** [comment]
I'll try the above. Running apt-key update does a check and tells me that GPG might not be installed "in your lab image?" Not sure yet. 

> [~/Development/Python/covidvu-help]$ docker build --tag dlwhitehurst/covidvu:1.0 .
Sending build context to Docker daemon  5.632kB
[WARNING]: Empty continuation line found in:
    RUN             apt-key update  && COPY            resources/_bash_profile /root/.bash_profile
[WARNING]: Empty continuation lines will become errors in a future release.
Step 1/8 : FROM            jupyter/datascience-notebook:latest
 ---> ce97927bafa2
Step 2/8 : MAINTAINER      covidvu.support@cime.net
 ---> Using cache
 ---> b4f50694ec32
Step 3/8 : USER            root
 ---> Using cache
 ---> 0621eb3626a4
Step 4/8 : RUN             apt-key update  && COPY            resources/_bash_profile /root/.bash_profile
 ---> Running in ec41cbb98396
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
The command '/bin/sh -c apt-key update  && COPY            resources/_bash_profile /root/.bash_profile' returned a non-zero code: 255

**Comment by pr3d4t0r** [comment]
Weird - not sure.

**Comment by pr3d4t0r** [comment]
Let's continue this on Slack -- the issue that started this was Theona compatibility with the server (it's been deprecated) and we want to avoid Conda altogether.  We found other Jupyter issues.  Swing by Slack when you have a minute.  I'm very curious about why your environment doesn't build.

**Comment by dlwhitehurst** [comment]
Added conda install of mkl only and upgrade of conda itself. Continued with pip installs. See PR https://github.com/VirusTrack/COVIDvu/pull/368
