### ISSUE TITLE
Analize the CSBS and NYT county data and help determine which to use

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#364]
Hi!

We need someone to help us analyze these two _**county**_ data sources:

- [ExpDev7](https://github.com/ExpDev07/coronavirus-tracker-api)
- [NYT covid-19-data](https://github.com/nytimes/covid-19-data)

## Information sought
- Number of counties reported in each data set for the time when you analyze them
- Statistical differences in the total (which is greater?)
- Per county comparison
- Per state comparison

Pick either data set as the ground truth, compare the other against it, report the differences as positive, negative, or same number of cases.  Bonus if you report that as an absolute percentage too.  Thanks in advance!

## CSBS data

We already have ExpDev7's ready to go.  All you have to do is deploy the JupyterLab image OR install a Python virtual env in the `./work` directory and run:
```bash
mkdir -p ./resources && ./countyraid
```
The files that you want will be listed in:
```
resources/
├── American-flag.png
├── counties-US-all.json
```
---
## New York Times data

We haven't pulled the repository yet, there are no tools analyzing it as this ticket is pulled.  The data is formatted as CSVs.

Find us in the COVIDvu Virus Track Slack channel #development or in the core team channel.

File any questions against this ticket or in the comm channels -- thanks!

**Comment by dlwhitehurst** [comment]
I'm looking at the NY Times data first and will use it as my baseline. I created a notebook in  /work/experiments directory. I'll add a pull request to merge the notebook into the issue branch.

**Comment by dlwhitehurst** [comment]
# US Counties (Reporting) - Total (2019) = 3142 (includes District of Columbia)
NYTimes Total = 1797
CSBS Total = <working>

**Comment by dlwhitehurst** [comment]
I have mistakes in my data handling. Will soon fix and resubmit the PR.

**Comment by dlwhitehurst** [comment]
Pull request submitted: https://github.com/VirusTrack/COVIDvu/pull/410
