### ISSUE TITLE
Integrate demographic data in global data feeds

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#409]
@kinabalu, @jaryaman - I will populate these when I get back, and merge all relevant tickets with it.

From Juvid: _Population size for all US states and all countries is what I need. A breakdown by age and gender would also open up interesting possibilities._

**Comment by pr3d4t0r** [comment]
Duplicates #297

**Comment by jaryaman** [comment]
This dataset looks like what we need for countries
https://www.census.gov/data-tools/demo/idb/informationGateway.php

Full dataset can be downloaded here:
https://www2.census.gov/programs-surveys/international-programs/about/idb/idbzip.zip

**Comment by jaryaman** [comment]
@pr3d4t0r `./work/COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv` contains the population size for all US counties, which we can sum up to get the population size for all US states. Combined with #503 we should have all the population sizes of all the regions we are presenting, and can now start doing per-capita calculations, and also set the upper bound of the prediction priors to be guided by population size.
