### ISSUE TITLE
Consider offering a history back in time view of county data

### ISSUE THREAD

**Issue by kinabalu** [pr3d4t0r/COVIDvu#425]
In order to do this we'll have to store the daily data though, but it would be neat to see the progression over N days / weeks @ciurana? @jaryaman?

**Comment by jaryaman** [comment]
@kinabalu @pr3d4t0r JH CSSE released this last night
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv

We can get full historical time series for counties. I'll try and make some time to parse this. We should be able to quite drastically simplify `vujson` now, as we don't need to faff about with the archived data any more.
