### ISSUE TITLE
Clarify predictions visualization

### ISSUE THREAD

**Issue by jaryaman** [pr3d4t0r/COVIDvu#426]
@kinabalu I have a few (highly subjective) suggestions for the predictions visualization. Please feel free to take or leave them!

1. Only show predictions for future dates. There will therefore be a gap of white space of 1 day between data and predictions. I can either stop supplying you prediction data points for historical dates from the backend, or we can mute them from the frontend -- whichever you prefer. 
2. Remove "We are here", which will become obvious after implementing (1).
3. The 2.5% and 25% percentiles are shown as solid green lines. For consistency, colour them with the same rule as 97.5% and 75%, i.e. the colour of the shading
4.  Make the difference in transparency between the 95% and 50% confidence intervals more dramatic, so it's easier to see 
5.  Use red for prediction confidence intervals, it's more attention grabbing (although possibly also alarmist, especially subjective)
6. If we are only showing 1 country at a time for predictions, can we switch `showlegend=True` back on for the percentiles? See `covidvu.predict.plotWithCI` where I've switched this information back on. I don't think it'll overwhelm the user to show this information when there is only 1 country.

**Comment by kinabalu** [comment]
<img width="621" alt="Screen Shot 2020-03-31 at 8 07 39 AM" src="https://user-images.githubusercontent.com/56997/78042349-b6243880-7326-11ea-9cb6-f8d566dfa989.png">

I'm okay with some more color suggestions, I'd rather we don't use red

**Comment by jaryaman** [comment]
"dark shaded region = 50% confidence, light shaded region = 95% confidence"

**Comment by jaryaman** [comment]
Fewer numbers on x-hover. Just:

2.5 = "lower
mean = "mean"
97.5 = "upper"

And some means to link to a math info page. Make the legend simpler.

**Comment by jaryaman** [comment]
@kinabalu also some indication to the user that today's number will be between "lower" and "upper" by midnight tonight/end of day.

**Comment by kinabalu** [comment]
I think we've solved this with the note on predictions so closing.
