### ISSUE TITLE
Add twitter, Facebook and linkedin icons and links to footer

### ISSUE THREAD

**Issue by kinabalu** [pr3d4t0r/COVIDvu#436]
Make them bigger, more apparent, and add the icons. We use the FontAwesome SVG's, just look at how it is done for other buttons.

**Comment by pr3d4t0r** [comment]
Suggestion from Evon:  put it right across the very top, small icons, include PayPal donations button.  We can use Andrew's, Eugene's, Juvid's PayPal account - don't care whose, we'll square the beer money later.  We need to get feedback from the outside world.  As discussed with Evon at 1500 PDT, right before I posted this message.

**Comment by pr3d4t0r** [comment]
PayPal button:
```
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick" />
<input type="hidden" name="hosted_button_id" value="52U5RTY2YY3WS" />
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
</form>
```

**Comment by pr3d4t0r** [comment]
URL:  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=52U5RTY2YY3WS&source=url

**Comment by pr3d4t0r** [comment]
QR code -- all go to the same place.
![QR Code](https://user-images.githubusercontent.com/148262/78194424-f45a4e80-7431-11ea-831a-5bc1ab37e83d.png)

**Comment by pr3d4t0r** [comment]
WAIT - defining a new email address.

**Comment by pr3d4t0r** [comment]
Fixed.
![IMG_46EE54772C3E-1](https://user-images.githubusercontent.com/148262/78194734-d17c6a00-7432-11ea-825c-77178e27fb89.jpeg)

**Comment by lucasmarohn** [comment]
Working on this now.

**Comment by kinabalu** [comment]
This is done
