### ISSUE TITLE
URL for NY Government Services is Incorrect

### ISSUE THREAD

**Issue by bitspace** [pr3d4t0r/COVIDvu#448]
The current link to "Government Services" for New York is to the NYC page (https://www1.nyc.gov/site/doh/covid/covid-19-main.page) but should be the NY State page (https://coronavirus.health.ny.gov/home).

**Comment by dlwhitehurst** [comment]
Thanks for the update. I've created a pull request to fix to this. See PR https://github.com/VirusTrack/COVIDvu/pull/449
