### ISSUE TITLE
Update all the licensing notices from pr3d4t0r to VirusTrack path

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#471]

**Comment by pr3d4t0r** [comment]
Simple `awk` job, or Perl if someone wants to pitch in.  I don't want to change them in PyCharm if the update changes the formatting for the rest of the files, otherwise PyCharm is fine too.  It must include all bash, awk, etc. scripts.

**Comment by dlwhitehurst** [comment]
Done. See PR https://github.com/VirusTrack/COVIDvu/pull/474
