### ISSUE TITLE
Place a reference states:regions or a link to the Wikipedia page

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#48]
To decide:

- What I think is easiest - [`US_REGIONS`](https://github.com/pr3d4t0r/COVIDvu/blob/71457bed95f7bddcf831783eb9b24eaa9d63b29c/work/vujson.py#L29) in `work/vujson.py`
- [Census Bureau designated regions and divisions](https://en.wikipedia.org/wiki/List_of_regions_of_the_United_States#Census_Bureau-designated_regions_and_divisions)

I will attach a JSON dump of `US_REGIONS` here in case you want to use that, in a comment.

**Comment by pr3d4t0r** [comment]
`US_REGIONS` as a JSON object:

```
{
  "Northeast": [
    "CT",
    "MA",
    "ME",
    "NH",
    "NJ",
    "NY",
    "PA",
    "RI",
    "VT"
  ],
  "Midwest": [
    "IA",
    "IL",
    "IN",
    "KS",
    "MI",
    "MN",
    "MO",
    "ND",
    "NE",
    "OH",
    "SD",
    "WI"
  ],
  "South": [
    "AL",
    "AR",
    "DC",
    "DE",
    "FL",
    "GA",
    "KY",
    "LA",
    "MD",
    "MS",
    "NC",
    "OK",
    "SC",
    "TN",
    "TX",
    "VA",
    "WV"
  ],
  "West": [
    "AK",
    "AZ",
    "CA",
    "CO",
    "HI",
    "ID",
    "MT",
    "NM",
    "NV",
    "OR",
    "UT",
    "WA",
    "WY"
  ]
}
```

**Comment by kinabalu** [comment]
added between footer and content
