### ISSUE TITLE
Stats Button & Today Range

### ISSUE THREAD

**Issue by mattplaysbass** [pr3d4t0r/COVIDvu#519]
Could you consider changing the "Stats" to something more like "Daily Update", just that it might be more intuitive then!  Also, in the stats page, could there be a hover popup that states when "Today" begins?  Is it specific to the timezone of the user, or is it always midnight Greenwich Mean Time?

![image](https://user-images.githubusercontent.com/58751340/78721966-607afd80-78dd-11ea-81aa-48628d48f9ab.png)

**Comment by kinabalu** [comment]
Today and Yesterday feels pretty clear to me. We can add a tooltip though
