### ISSUE TITLE
Identify why test.virustrak.live can't render results from new bundles

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#531]

**Comment by pr3d4t0r** [comment]
test.virustrack.live has the latest bundles generated off the database, not by passing through the CSSE + BNO patches.  Please help identify why they don't render.  The legacy and new bundles structure is identical.  Thanks!

**Comment by kinabalu** [comment]
No `/site-data/last-update.txt`. I'm pushing a new version that will just throw a 404 when it's not found so it's not fatal like that.
