### ISSUE TITLE
Counties Tables & Graphs are Showing as Zero Cases/Deaths

### ISSUE THREAD

**Issue by mattplaysbass** [pr3d4t0r/COVIDvu#562]
On both the Table and Graph functions in the "U.S. Counties" tab there is no information:

![image](https://user-images.githubusercontent.com/58751340/79136057-3904b480-7d65-11ea-8b31-92de8e09dd7b.png)

![image](https://user-images.githubusercontent.com/58751340/79136126-59347380-7d65-11ea-83d4-602db2a23111.png)

**Comment by kinabalu** [comment]
Looks like the counties data shape has changed so we've now got time-series data there, will fix this shortly.
