### ISSUE TITLE
Fix the date format in data files

### ISSUE THREAD

**Issue by kinabalu** [pr3d4t0r/COVIDvu#84]
The date format being used until 3/11 was MM/DD/YYYY. Would prefer YYYY-MM-DD as we have to transform on our end. But at the very least needs to be consistent. The latest day is now MM-DD-YYYY.

**Comment by pr3d4t0r** [comment]
This is the format we use in all our data - ISO date.  Where did you see different?  It may come like that from the sources, not from us.  Please expand so I can address.
