### ISSUE TITLE
Odd data issues in the country list

### ISSUE THREAD

**Issue by kinabalu** [pr3d4t0r/COVIDvu#98]
For any country data assume that the totals are for the last reported date shown in the json available at https://virustrack.live/site-data/confirmed.json.

!Global has 125,865 cases. !Outside Mainland China has 125,865. How is that possible? If it's truly !Outside Mainland China it should be 125,865 - 80,793 or 45,072.

There is an entry for China with 80,921 and an entry for Mainland China with 80,793.

We have South Korea 7869, and Korea, South 7755.

We have United Kingdom 459 and UK 456

Czech Republic 94 and Cezchia 91

Taiwan* 48 and Taiwan 48

There's an Iran with cases, but also Iran (Islamic Republic of) with 0

There's a Vietnam and a Viet Nam

**Comment by pr3d4t0r** [comment]
Hola.

I'll work on this as part of [issue 0096](https://github.com/pr3d4t0r/COVIDvu/issues/96) - they are related.

**Comment by pr3d4t0r** [comment]
These are the issues I mentioned with the [original data source](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series).  If you open this in Vim or `awk`/`grep` it, you'll find all these weird data entries.  They're doing a shoddy job of maintaining this thing.
