### ISSUE TITLE
Latest dates showing up with 0s for region

### ISSUE THREAD

**Issue by kinabalu** [pr3d4t0r/COVIDvu#99]
Latest dates if looking at the UI are showing 0's for all regional data. so Midwest, Northeast, South and West all show 0 on the last date entry at https://virustrack.live/site-data/confirmed-US-Regions.json

**Comment by pr3d4t0r** [comment]
Also in [issue 0096](https://github.com/pr3d4t0r/COVIDvu/issues/96) now.
